### ISSUE TITLE
Dependency on postgresql

### ISSUE THREAD

**Issue by warnes** [kirpit/django-sample-app#2]
The install instruction neglect to mention the dependency on postgresql.

**Comment by Avinash-Raj** [comment]
for me it shows
```Python

Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/gemini/projects/OCR/python_ocr_tutorial/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/gemini/projects/OCR/python_ocr_tutorial/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/home/gemini/projects/OCR/python_ocr_tutorial/env/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/gemini/projects/OCR/python_ocr_tutorial/env/local/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/gemini/projects/OCR/python_ocr_tutorial/env/local/lib/python2.7/site-packages/django/apps/config.py", line 112, in create
    mod = import_module(mod_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named {{ project_name }}
```
